version: "3.9"

services:
  rag-dashboard:
    build: .
    image: edu-rag:latest
    container_name: edu-rag-dashboard
    ports:
      - "8000:8000"
    environment:
      - VECTOR_DB_PATH=/app/vector_db
      - USE_RERANKER=0   # optional: keeps image light
    volumes:
        - ./vector_db:/app/vector_db
        - ./data:/app/data        # if you want live data edits
        - ./metrics:/app/metrics  # optional, for system.json
    restart: unless-stopped